name: CI

on:
  push:
    paths-ignore:
    - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Prepare
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: 16
        cache: 'gradle'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Restore and export service account to ENV for GCS remote cache
      run: |
        echo $GCS_SERVICE_ACCOUNT | base64 --decode --ignore-garbage > service.json
        echo "GOOGLE_APPLICATION_CREDENTIALS=service.json" >> $GITHUB_ENV
      if: env.GCS_SERVICE_ACCOUNT
      env:
        GCS_SERVICE_ACCOUNT: ${{ secrets.GCS_SERVICE_ACCOUNT }}

    # Execute
    - name: Build with Gradle
      run: ./gradlew assembleArchive test --profile

    # Post
    - uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: |
          build/libs/*.jar
          build/distributions
      if: always()
    - uses: actions/upload-artifact@v2
      with:
        name: reports
        path: |
          build/test-results/test/*.xml
          build/reports/
      if: always()

  integrate_test:
    runs-on: ubuntu-latest
    needs: build
    env:
      GOOGLE_APPLICATION_CREDENTIALS: service.json
    strategy:
      matrix:
        java: [8, 11, 16]
    steps:
      # Prepare
      - uses: actions/checkout@v2
      - name: Decrypt service account json
        env:
          GCS_SERVICE_ACCOUNT: ${{ secrets.GCS_SERVICE_ACCOUNT }}
        run: echo $GCS_SERVICE_ACCOUNT | base64 --decode --ignore-garbage > service.json
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}
      - uses: actions/download-artifact@v2
        with:
          name: artifacts
      - run: tar -xvf distributions/skw.tar

      # Integrate test
      - name: Run integratation test script
        run: |
          .github/workflows/integration_test.sh \
            -s ./skw/bin/skw \
            -b "gs://kesin11_bazel_cache" \
            -k "github_actions" \
            -p "java${{ matrix.java }}" \
            -t "java${{ matrix.java }}"
        env:
          GITHUB_RUN_NUMBER: ${{ github.run_number }}

  dogfooding_deb:
    runs-on: ubuntu-latest
    needs: build
    container: "ubuntu:latest"
    env:
      GOOGLE_APPLICATION_CREDENTIALS: service.json
    steps:
      # Prepare
      - name: Decrypt service account json
        env:
          GCS_SERVICE_ACCOUNT: ${{ secrets.GCS_SERVICE_ACCOUNT }}
        run: echo $GCS_SERVICE_ACCOUNT | base64 --decode --ignore-garbage > service.json
      - uses: actions/download-artifact@v2
        with:
          name: artifacts
      - name: Install skw from .deb
        run: |
          apt update
          apt install -y ./distributions/skw_amd64.deb

      # Execute
      - name: Check installed path
        run: which skw | grep "/usr/local/bin/skw"
      - name: Upload own jar to GCS
        run: |
          skw upload \
            -b "gs://kesin11_bazel_cache" \
            -k "dogfooding" \
            -t "${{ github.sha }}" -t "latest" \
            -p "dogfooding/${{ github.run_number }}" \
            ./distributions/skw.jar
