name: Release
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    name: Build artifacts
    runs-on: ubuntu-latest
    steps:
      # Prepare
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Restore and export service account to ENV for GCS remote cache
        run: |
          echo $GCS_SERVICE_ACCOUNT | base64 --decode --ignore-garbage > service.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=service.json" >> $GITHUB_ENV
        if: env.GCS_SERVICE_ACCOUNT
        env:
          GCS_SERVICE_ACCOUNT: ${{ secrets.GCS_SERVICE_ACCOUNT }}

      # Build
      - name: Build with Gradle
        run: ./gradlew assembleArchive
      
      # Post
      - uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: |
            build/libs/skw.jar
            build/distributions

  github_releases:
    name: Upload github releases
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: artifacts
      - name: Upload assets
        run: |
          gh release upload --clobber "${GITHUB_REF#refs/*/}" \
            libs/skw.jar \
            distributions/skw.tar \
            distributions/skw.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
