name: Release
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    name: Build artifacts
    runs-on: ubuntu-latest
    steps:
      # Prepare
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Restore and export service account to ENV for GCS remote cache
        run: |
          echo $GCS_SERVICE_ACCOUNT | base64 --decode --ignore-garbage > service.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=service.json" >> $GITHUB_ENV
        if: env.GCS_SERVICE_ACCOUNT
        env:
          GCS_SERVICE_ACCOUNT: ${{ secrets.GCS_SERVICE_ACCOUNT }}

      # Build
      - name: Build with Gradle
        run: ./gradlew assembleArchive
      
      # Post
      - uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: |
            build/libs/skw.jar
            build/distributions

  github_releases:
    name: Upload github releases
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: artifacts
      - name: Upload assets
        run: |
          gh release upload --clobber "${GITHUB_REF#refs/*/}" \
            libs/skw.jar \
            distributions/skw.tar \
            distributions/skw.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  bump_brew:
    name: Bump homebrew formula
    runs-on: ubuntu-latest
    needs: github_releases
    steps:
      - name: Extract version
        id: extract-version
        run: |
          printf "::set-output name=%s::%s\n" tag-name "${GITHUB_REF#refs/tags/}"
      - uses: mislav/bump-homebrew-formula-action@v1
        with:
          formula-name: skw
          formula-path: Formula/skw.rb
          homebrew-tap: Kesin11/homebrew-tap
          base-branch: main
          download-url: "https://github.com/Kesin11/SkyWarehouse/releases/download/${{ steps.extract-version.outputs.tag-name }}/skw.jar"
          commit-message: |
            {{formulaName}} {{version}}

            Created by https://github.com/mislav/bump-homebrew-formula-action
        env:
          COMMITTER_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
