name: Ship js trigger
on:
  pull_request:
    types:
      - closed
jobs:
  build:
    name: Create Github Releases and push tag
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'releases/v')
    steps:
      # prepare
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: main
          # Workaround for trigger 'push tag' workflow
          # see: https://github.community/t/action-does-not-trigger-another-on-push-tag-action/17148/4
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - uses: actions/setup-node@v2
        with:
          registry-url: "https://registry.npmjs.org"

      - run: npx shipjs trigger
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          # SLACK_INCOMING_HOOK: ${{ secrets.SLACK_INCOMING_HOOK }}
  # Shipjs create new git tag and push. It triggers next workflow.
